// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: nsfw.proto

package grpcModels

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NSFW_Detect_FullMethodName       = "/proto.NSFW/Detect"
	NSFW_DetectLabels_FullMethodName = "/proto.NSFW/DetectLabels"
	NSFW_Analyze_FullMethodName      = "/proto.NSFW/Analyze"
)

// NSFWClient is the client API for NSFW service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NSFWClient interface {
	Detect(ctx context.Context, in *NSFWRequest, opts ...grpc.CallOption) (*NSFWResponse, error)
	DetectLabels(ctx context.Context, in *NSFWLabelsRequest, opts ...grpc.CallOption) (*NSFWLabels, error)
	Analyze(ctx context.Context, in *NSFWRequest, opts ...grpc.CallOption) (*Analysis, error)
}

type nSFWClient struct {
	cc grpc.ClientConnInterface
}

func NewNSFWClient(cc grpc.ClientConnInterface) NSFWClient {
	return &nSFWClient{cc}
}

func (c *nSFWClient) Detect(ctx context.Context, in *NSFWRequest, opts ...grpc.CallOption) (*NSFWResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NSFWResponse)
	err := c.cc.Invoke(ctx, NSFW_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWClient) DetectLabels(ctx context.Context, in *NSFWLabelsRequest, opts ...grpc.CallOption) (*NSFWLabels, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NSFWLabels)
	err := c.cc.Invoke(ctx, NSFW_DetectLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWClient) Analyze(ctx context.Context, in *NSFWRequest, opts ...grpc.CallOption) (*Analysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Analysis)
	err := c.cc.Invoke(ctx, NSFW_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSFWServer is the server API for NSFW service.
// All implementations must embed UnimplementedNSFWServer
// for forward compatibility.
type NSFWServer interface {
	Detect(context.Context, *NSFWRequest) (*NSFWResponse, error)
	DetectLabels(context.Context, *NSFWLabelsRequest) (*NSFWLabels, error)
	Analyze(context.Context, *NSFWRequest) (*Analysis, error)
	mustEmbedUnimplementedNSFWServer()
}

// UnimplementedNSFWServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNSFWServer struct{}

func (UnimplementedNSFWServer) Detect(context.Context, *NSFWRequest) (*NSFWResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedNSFWServer) DetectLabels(context.Context, *NSFWLabelsRequest) (*NSFWLabels, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectLabels not implemented")
}
func (UnimplementedNSFWServer) Analyze(context.Context, *NSFWRequest) (*Analysis, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedNSFWServer) mustEmbedUnimplementedNSFWServer() {}
func (UnimplementedNSFWServer) testEmbeddedByValue()              {}

// UnsafeNSFWServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NSFWServer will
// result in compilation errors.
type UnsafeNSFWServer interface {
	mustEmbedUnimplementedNSFWServer()
}

func RegisterNSFWServer(s grpc.ServiceRegistrar, srv NSFWServer) {
	// If the following call panics, it indicates UnimplementedNSFWServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NSFW_ServiceDesc, srv)
}

func _NSFW_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSFWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFW_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWServer).Detect(ctx, req.(*NSFWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFW_DetectLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSFWLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWServer).DetectLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFW_DetectLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWServer).DetectLabels(ctx, req.(*NSFWLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFW_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSFWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFW_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWServer).Analyze(ctx, req.(*NSFWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NSFW_ServiceDesc is the grpc.ServiceDesc for NSFW service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NSFW_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NSFW",
	HandlerType: (*NSFWServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _NSFW_Detect_Handler,
		},
		{
			MethodName: "DetectLabels",
			Handler:    _NSFW_DetectLabels_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _NSFW_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsfw.proto",
}
