// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: nsfw.proto

package grpcModels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NSFWRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base64        string                 `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSFWRequest) Reset() {
	*x = NSFWRequest{}
	mi := &file_nsfw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSFWRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSFWRequest) ProtoMessage() {}

func (x *NSFWRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSFWRequest.ProtoReflect.Descriptor instead.
func (*NSFWRequest) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{0}
}

func (x *NSFWRequest) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *NSFWRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type NSFWResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsfwPicture   bool                   `protobuf:"varint,1,opt,name=nsfwPicture,proto3" json:"nsfwPicture,omitempty"`
	NsfwText      bool                   `protobuf:"varint,2,opt,name=nsfwText,proto3" json:"nsfwText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSFWResponse) Reset() {
	*x = NSFWResponse{}
	mi := &file_nsfw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSFWResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSFWResponse) ProtoMessage() {}

func (x *NSFWResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSFWResponse.ProtoReflect.Descriptor instead.
func (*NSFWResponse) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{1}
}

func (x *NSFWResponse) GetNsfwPicture() bool {
	if x != nil {
		return x.NsfwPicture
	}
	return false
}

func (x *NSFWResponse) GetNsfwText() bool {
	if x != nil {
		return x.NsfwText
	}
	return false
}

type NSFWLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base64        string                 `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSFWLabelsRequest) Reset() {
	*x = NSFWLabelsRequest{}
	mi := &file_nsfw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSFWLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSFWLabelsRequest) ProtoMessage() {}

func (x *NSFWLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSFWLabelsRequest.ProtoReflect.Descriptor instead.
func (*NSFWLabelsRequest) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{2}
}

func (x *NSFWLabelsRequest) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *NSFWLabelsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type NSFWLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drawings      float32                `protobuf:"fixed32,1,opt,name=Drawings,proto3" json:"Drawings,omitempty"`
	Hentai        float32                `protobuf:"fixed32,2,opt,name=Hentai,proto3" json:"Hentai,omitempty"`
	Neutral       float32                `protobuf:"fixed32,3,opt,name=Neutral,proto3" json:"Neutral,omitempty"`
	Porn          float32                `protobuf:"fixed32,4,opt,name=Porn,proto3" json:"Porn,omitempty"`
	Sexy          float32                `protobuf:"fixed32,5,opt,name=Sexy,proto3" json:"Sexy,omitempty"`
	NsfwText      bool                   `protobuf:"varint,6,opt,name=nsfwText,proto3" json:"nsfwText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSFWLabels) Reset() {
	*x = NSFWLabels{}
	mi := &file_nsfw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSFWLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSFWLabels) ProtoMessage() {}

func (x *NSFWLabels) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSFWLabels.ProtoReflect.Descriptor instead.
func (*NSFWLabels) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{3}
}

func (x *NSFWLabels) GetDrawings() float32 {
	if x != nil {
		return x.Drawings
	}
	return 0
}

func (x *NSFWLabels) GetHentai() float32 {
	if x != nil {
		return x.Hentai
	}
	return 0
}

func (x *NSFWLabels) GetNeutral() float32 {
	if x != nil {
		return x.Neutral
	}
	return 0
}

func (x *NSFWLabels) GetPorn() float32 {
	if x != nil {
		return x.Porn
	}
	return 0
}

func (x *NSFWLabels) GetSexy() float32 {
	if x != nil {
		return x.Sexy
	}
	return 0
}

func (x *NSFWLabels) GetNsfwText() bool {
	if x != nil {
		return x.NsfwText
	}
	return false
}

type Analysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Nsfw          float32                `protobuf:"fixed32,2,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	NsfwText      bool                   `protobuf:"varint,3,opt,name=nsfwText,proto3" json:"nsfwText,omitempty"`
	Labels        *NSFWLabels            `protobuf:"bytes,4,opt,name=labels,proto3" json:"labels,omitempty"`
	Photo         *ScoreMap              `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Anime         *ScoreMap              `protobuf:"bytes,6,opt,name=anime,proto3" json:"anime,omitempty"`
	Detections    []*Detection           `protobuf:"bytes,7,rep,name=detections,proto3" json:"detections,omitempty"`
	Models        []*ModelInfo           `protobuf:"bytes,8,rep,name=models,proto3" json:"models,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,9,opt,name=elapsedMs,proto3" json:"elapsedMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_nsfw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{4}
}

func (x *Analysis) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *Analysis) GetNsfw() float32 {
	if x != nil {
		return x.Nsfw
	}
	return 0
}

func (x *Analysis) GetNsfwText() bool {
	if x != nil {
		return x.NsfwText
	}
	return false
}

func (x *Analysis) GetLabels() *NSFWLabels {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Analysis) GetPhoto() *ScoreMap {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *Analysis) GetAnime() *ScoreMap {
	if x != nil {
		return x.Anime
	}
	return nil
}

func (x *Analysis) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *Analysis) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Analysis) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ScoreMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Scores        map[string]float32     `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreMap) Reset() {
	*x = ScoreMap{}
	mi := &file_nsfw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreMap) ProtoMessage() {}

func (x *ScoreMap) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreMap.ProtoReflect.Descriptor instead.
func (*ScoreMap) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreMap) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ScoreMap) GetScores() map[string]float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Box           *Box                   `protobuf:"bytes,3,opt,name=box,proto3" json:"box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_nsfw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{6}
}

func (x *Detection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detection) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Detection) GetBox() *Box {
	if x != nil {
		return x.Box
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float32                `protobuf:"fixed32,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float32                `protobuf:"fixed32,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_nsfw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{7}
}

func (x *Box) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Box) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Box) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Box) GetH() float32 {
	if x != nil {
		return x.H
	}
	return 0
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_nsfw_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{8}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModelInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_nsfw_proto protoreflect.FileDescriptor

const file_nsfw_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nsfw.proto\x12\x05proto\"A\n" +
	"\vNSFWRequest\x12\x16\n" +
	"\x06base64\x18\x01 \x01(\tR\x06base64\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"L\n" +
	"\fNSFWResponse\x12 \n" +
	"\vnsfwPicture\x18\x01 \x01(\bR\vnsfwPicture\x12\x1a\n" +
	"\bnsfwText\x18\x02 \x01(\bR\bnsfwText\"G\n" +
	"\x11NSFWLabelsRequest\x12\x16\n" +
	"\x06base64\x18\x01 \x01(\tR\x06base64\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\x9e\x01\n" +
	"\n" +
	"NSFWLabels\x12\x1a\n" +
	"\bDrawings\x18\x01 \x01(\x02R\bDrawings\x12\x16\n" +
	"\x06Hentai\x18\x02 \x01(\x02R\x06Hentai\x12\x18\n" +
	"\aNeutral\x18\x03 \x01(\x02R\aNeutral\x12\x12\n" +
	"\x04Porn\x18\x04 \x01(\x02R\x04Porn\x12\x12\n" +
	"\x04Sexy\x18\x05 \x01(\x02R\x04Sexy\x12\x1a\n" +
	"\bnsfwText\x18\x06 \x01(\bR\bnsfwText\"\xc7\x02\n" +
	"\bAnalysis\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x12\n" +
	"\x04nsfw\x18\x02 \x01(\x02R\x04nsfw\x12\x1a\n" +
	"\bnsfwText\x18\x03 \x01(\bR\bnsfwText\x12)\n" +
	"\x06labels\x18\x04 \x01(\v2\x11.proto.NSFWLabelsR\x06labels\x12%\n" +
	"\x05photo\x18\x05 \x01(\v2\x0f.proto.ScoreMapR\x05photo\x12%\n" +
	"\x05anime\x18\x06 \x01(\v2\x0f.proto.ScoreMapR\x05anime\x120\n" +
	"\n" +
	"detections\x18\a \x03(\v2\x10.proto.DetectionR\n" +
	"detections\x12(\n" +
	"\x06models\x18\b \x03(\v2\x10.proto.ModelInfoR\x06models\x12\x1c\n" +
	"\telapsedMs\x18\t \x01(\x03R\telapsedMs\"\x90\x01\n" +
	"\bScoreMap\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x123\n" +
	"\x06scores\x18\x02 \x03(\v2\x1b.proto.ScoreMap.ScoresEntryR\x06scores\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"U\n" +
	"\tDetection\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1c\n" +
	"\x03box\x18\x03 \x01(\v2\n" +
	".proto.BoxR\x03box\"=\n" +
	"\x03Box\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x02R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x02R\x01h\"G\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha2562\xac\x01\n" +
	"\x04NSFW\x123\n" +
	"\x06Detect\x12\x12.proto.NSFWRequest\x1a\x13.proto.NSFWResponse\"\x00\x12=\n" +
	"\fDetectLabels\x12\x18.proto.NSFWLabelsRequest\x1a\x11.proto.NSFWLabels\"\x00\x120\n" +
	"\aAnalyze\x12\x12.proto.NSFWRequest\x1a\x0f.proto.Analysis\"\x00B\x0eZ\f./grpcModelsb\x06proto3"

var (
	file_nsfw_proto_rawDescOnce sync.Once
	file_nsfw_proto_rawDescData []byte
)

func file_nsfw_proto_rawDescGZIP() []byte {
	file_nsfw_proto_rawDescOnce.Do(func() {
		file_nsfw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nsfw_proto_rawDesc), len(file_nsfw_proto_rawDesc)))
	})
	return file_nsfw_proto_rawDescData
}

var file_nsfw_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_nsfw_proto_goTypes = []any{
	(*NSFWRequest)(nil),       // 0: proto.NSFWRequest
	(*NSFWResponse)(nil),      // 1: proto.NSFWResponse
	(*NSFWLabelsRequest)(nil), // 2: proto.NSFWLabelsRequest
	(*NSFWLabels)(nil),        // 3: proto.NSFWLabels
	(*Analysis)(nil),          // 4: proto.Analysis
	(*ScoreMap)(nil),          // 5: proto.ScoreMap
	(*Detection)(nil),         // 6: proto.Detection
	(*Box)(nil),               // 7: proto.Box
	(*ModelInfo)(nil),         // 8: proto.ModelInfo
	nil,                       // 9: proto.ScoreMap.ScoresEntry
}
var file_nsfw_proto_depIdxs = []int32{
	3,  // 0: proto.Analysis.labels:type_name -> proto.NSFWLabels
	5,  // 1: proto.Analysis.photo:type_name -> proto.ScoreMap
	5,  // 2: proto.Analysis.anime:type_name -> proto.ScoreMap
	6,  // 3: proto.Analysis.detections:type_name -> proto.Detection
	8,  // 4: proto.Analysis.models:type_name -> proto.ModelInfo
	9,  // 5: proto.ScoreMap.scores:type_name -> proto.ScoreMap.ScoresEntry
	7,  // 6: proto.Detection.box:type_name -> proto.Box
	0,  // 7: proto.NSFW.Detect:input_type -> proto.NSFWRequest
	2,  // 8: proto.NSFW.DetectLabels:input_type -> proto.NSFWLabelsRequest
	0,  // 9: proto.NSFW.Analyze:input_type -> proto.NSFWRequest
	1,  // 10: proto.NSFW.Detect:output_type -> proto.NSFWResponse
	3,  // 11: proto.NSFW.DetectLabels:output_type -> proto.NSFWLabels
	4,  // 12: proto.NSFW.Analyze:output_type -> proto.Analysis
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_nsfw_proto_init() }
func file_nsfw_proto_init() {
	if File_nsfw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nsfw_proto_rawDesc), len(file_nsfw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nsfw_proto_goTypes,
		DependencyIndexes: file_nsfw_proto_depIdxs,
		MessageInfos:      file_nsfw_proto_msgTypes,
	}.Build()
	File_nsfw_proto = out.File
	file_nsfw_proto_goTypes = nil
	file_nsfw_proto_depIdxs = nil
}
